<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analytics PDF</title>
</head>

<style>
    .text-center {
        text-align: center;
    }

    #logo-header {
        width: 40px;
    }

    h3 {
        margin-bottom: 2px;
    }

    h4 {
        padding: 3px;
        margin-bottom: 3px;
    }

    p {
        margin-top: 0px;
    }

    table {
        width: 100%;
        table-layout: fixed;
        margin: auto;
        background-color: #fff;
    }

    table,
    th,
    td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th,
    td {
        padding: 5px;
        vertical-align: middle;
    }
</style>

<body>
    <header>
        <div class="text-center">
            <img src="<?= $logo ?>" alt="TUP Logo" id="logo-header">
            <h3>Technological University of the Philippines - Taguig</h3>
            <p>This document is generated by https://tupt-rms.com.</p>
        </div>
    </header>
    <hr>

    <!-- [ Note ] -->
    <small>
        <i>Note: The analytics in this document are based on the current system data as of <?= $datenow ?>.
            Please be aware that this data is continuously updated and may differ with future reports.</i>
    </small>


    <!-- [ Department ] -->
    <h4>Department Report</h4>
    <table>
        <tr>
            <th>Department</th>
            <th>No. Employee</th>
            <th>Percentage</th>
        </tr>

        <?php foreach ($analytics['categories'] as $category): ?>
            <tr>
                <td><?= $category['department_category_code'] ?></td>
                <td class="text-center"><?= $category['count'] ?></td>
                <td class="text-center"><?= $category['count'] / $analytics['allusers'] * 100 . " %" ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <!-- [ Employee ] -->
    <h4>Employee Report</h4>
    <table>
        <tr>
            <th>Employee Type</th>
            <th>No. Employee</th>
            <th>Percentage</th>
        </tr>

        <?php foreach ($analytics['employeetypes'] as $employee): ?>
            <tr>
                <td><?= $employee['employee_type_name'] ?></td>
                <td class="text-center"><?= $employee['count'] ?></td>
                <td class="text-center"><?= $employee['count'] / $analytics['allusers'] * 100 . " %" ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <!-- [ Other ] -->
    <h4>More Reports</h4>
    <table>
        <tr>
            <th>Category</th>
            <th>Count</th>
        </tr>

        <tr>
            <td>Masters</td>
            <td class="text-center"><?= $analytics['masters'] ?></td>
        </tr>
        <tr>
            <td>Doctorate</td>
            <td class="text-center"><?= $analytics['doctorate'] ?></td>
        </tr>
        <tr>
            <td>Baccalaureate</td>
            <td class="text-center"><?= $analytics['baccalaureate'] ?></td>
        </tr>
        <tr>
            <td>Retired</td>
            <td class="text-center"><?= $analytics['retired'] ?></td>
        </tr>
        <tr>
            <td>Senior</td>
            <td class="text-center"><?= $analytics['senior'] ?></td>
        </tr>
        <tr>
            <td>Male</td>
            <td class="text-center"><?= $analytics['male'] ?></td>
        </tr>
        <tr>
            <td>Female</td>
            <td class="text-center"><?= $analytics['female'] ?></td>
        </tr>
    </table>
</body>

</html>